# Generated by Django 5.2.3 on 2025-06-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_customuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentinfo",
            name="academic_year",
            field=models.CharField(
                choices=[
                    ("1", "First Year"),
                    ("2", "Second Year"),
                    ("3", "Third Year"),
                    ("4", "Fourth Year"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="studentinfo",
            name="department",
            field=models.CharField(
                choices=[
                    ("CS", "Computer Science"),
                    ("IT", "Information Technology"),
                    ("IS", "Information Systems"),
                ],
                max_length=100,
            ),
        ),
    ]
