# Generated by Django 5.2.3 on 2025-06-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_student_delete_studentinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="academic_year",
            field=models.CharField(
                choices=[
                    ("1", "First Year"),
                    ("2", "Second Year"),
                    ("3", "Third Year"),
                    ("4", "Fourth Year"),
                ],
                default="addsdsd",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="department",
            field=models.CharField(
                choices=[
                    ("CS", "Computer Science"),
                    ("IT", "Information Technology"),
                    ("IS", "Information Systems"),
                ],
                default="CS",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="full_name",
            field=models.CharField(default="Seif Wael", max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Student",
        ),
    ]
