# Generated by Django 5.2.3 on 2025-06-13 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("doctor", models.CharField(max_length=255)),
                ("department", models.CharField(max_length=255)),
                ("credit_hours", models.IntegerField()),
                ("students", models.IntegerField(blank=True, null=True)),
                ("course_description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="CoursePDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pdf_file", models.FileField(upload_to="course_pdfs/")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdfs",
                        to="academy.course",
                    ),
                ),
            ],
        ),
    ]
