# Generated by Django 5.2 on 2025-06-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
