# Generated by Django 5.2 on 2025-06-22 12:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0002_course_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursepdf",
            name="pdf_file",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True
            ),
        ),
    ]
