# Generated by Django 5.2.3 on 2025-06-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="test",
            name="title",
        ),
        migrations.AddField(
            model_name="test",
            name="status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Graded", "Graded")],
                default="Pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="due_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="test",
            name="link",
            field=models.URLField(
                default="https://www.google.com/search?q=google+forms&oq=google+for&gs_lcrp=EgZjaHJvbWUqDwgAEAAYFBiHAhixAxiABDIPCAAQABgUGIcCGLEDGIAEMgYIARBFGDkyDQgCEAAYgwEYsQMYgAQyBggDEEUYQDIHCAQQABiABDIHCAUQABiABDIGCAYQRRg8MgYIBxBFGDyoAgCwAgA&sourceid=chrome&ie=UTF-8",
                max_length=500,
            ),
            preserve_default=False,
        ),
    ]
