# Generated by Django 5.2.3 on 2025-06-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0002_remove_test_created_at_remove_test_title_test_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="points",
        ),
        migrations.RemoveField(
            model_name="test",
            name="status",
        ),
        migrations.AlterField(
            model_name="test",
            name="due_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="test",
            name="link",
            field=models.URLField(),
        ),
    ]
