# Generated by Django 5.2 on 2025-06-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0003_remove_test_points_remove_test_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="test",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="test",
            name="title",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="test",
            name="type",
            field=models.CharField(
                choices=[
                    ("Quiz", "Quiz"),
                    ("Project", "Project"),
                    ("Homework", "Homework"),
                    ("Lab", "Lab"),
                    ("Report", "Report"),
                    ("Other", "Other"),
                ],
                default="Homework",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
