# Generated by Django 5.2 on 2025-06-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="title",
            field=models.CharField(default="Unnamed Schedule", max_length=255),
        ),
    ]
