# Generated by Django 5.2 on 2025-06-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0002_schedule_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schedule",
            options={"ordering": ["stage", "schedule_type", "department"]},
        ),
        migrations.RenameField(
            model_name="schedule",
            old_name="uploaded_at",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="schedule",
            name="department",
            field=models.CharField(
                choices=[
                    ("General", "General (No specific department)"),
                    ("CS", "Computer Science"),
                    ("IT", "Information Technology"),
                    ("IS", "Information Systems"),
                ],
                default="General",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="schedules_images/"
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="schedule_type",
            field=models.CharField(
                choices=[
                    ("Lectures", "Lectures Schedule"),
                    ("Exams", "Exams Schedule"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="stage",
            field=models.CharField(
                choices=[
                    ("First", "First Year"),
                    ("Second", "Second Year"),
                    ("Third", "Third Year"),
                    ("Fourth", "Fourth Year"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="schedule",
            unique_together={("stage", "schedule_type", "department")},
        ),
    ]
