# Generated by Django 5.2 on 2025-06-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0003_alter_schedule_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schedule",
            options={},
        ),
        migrations.RenameField(
            model_name="schedule",
            old_name="created_at",
            new_name="uploaded_at",
        ),
        migrations.AlterUniqueTogether(
            name="schedule",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="image",
            field=models.ImageField(default="", upload_to="schedules/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="schedule",
            name="schedule_type",
            field=models.CharField(
                choices=[("lecture", "Lecture Schedule"), ("exam", "Exam Schedule")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="stage",
            field=models.IntegerField(
                choices=[
                    (1, "First Year"),
                    (2, "Second Year"),
                    (3, "Third Year"),
                    (4, "Fourth Year"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="title",
            field=models.CharField(default="Unnamed Schedule", max_length=255),
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="department",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="updated_at",
        ),
    ]
