# Generated by Django 5.2 on 2025-06-22 12:17

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0004_alter_schedule_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to="damanhour/Section/images/",
            ),
        ),
    ]
