# Generated by Django 5.2 on 2025-06-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0005_alter_schedule_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CS", "Computer Science"),
                    ("IT", "Information Technology"),
                    ("IS", "Information Systems"),
                    ("General", "General (For 1st and 2nd year)"),
                ],
                default="General",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="schedule",
            unique_together={("stage", "schedule_type", "department")},
        ),
    ]
